
name: build-offline-win64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish self-contained win-x64
        run: |
          dotnet publish GLLRV.DesktopApp/GLLRV.DesktopApp.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishReadyToRun=true -o publish/win-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GLLRV_offline_win64
          path: publish/win-x64/**
